# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vatrena' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vatrena

pod 'Firebase/Core'
pod 'PKHUD', '~> 4.0'

end
